version: '24.0.7'
services:
  gateway:
    build: gateway
    image:
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image:
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres1732

  db:
    image: postgres:14-alpine
    container_name: shareit-database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1732