DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.items;
DROP TABLE IF EXISTS public.bookings;
DROP TABLE IF EXISTS public.comments;

CREATE table IF NOT EXISTS public.users (
user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_name varchar NOT NULL,
	email varchar NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id),
	CONSTRAINT users_un UNIQUE (email)
);

CREATE table IF NOT EXISTS public.items (
	item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	item_name varchar NOT NULL,
	description varchar NOT NULL,
	is_available boolean NULL,
	owner_id bigint NOT NULL,
	CONSTRAINT items_pk PRIMARY KEY (item_id),
	CONSTRAINT items_fk FOREIGN KEY (owner_id) REFERENCES public.users(user_id)
);

CREATE TABLE IF NOT EXISTS public.bookings (
	booking_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	start_date timestamp without time zone NOT NULL,
	end_date timestamp without time zone NOT NULL,
	status varchar NOT NULL,
	booker_id bigint NOT NULL,
	item_id bigint NOT NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (booking_id),
	CONSTRAINT bookings_fk FOREIGN KEY (booker_id) REFERENCES public.users(user_id),
	CONSTRAINT bookings_fk_1 FOREIGN KEY (item_id) REFERENCES public.items(item_id)
);

CREATE TABLE IF NOT EXISTS public.comments (
	comment_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	text varchar NOT NULL,
	created timestamp without time zone NOT NULL,
	item_id bigint NOT NULL,
	author_id bigint NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (comment_id),
	CONSTRAINT comments_fk FOREIGN KEY (author_id) REFERENCES public.users(user_id),
	CONSTRAINT comments_fk_1 FOREIGN KEY (item_id) REFERENCES public.items(item_id)
);